### ISSUE TITLE
Конфигурация след deployment

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#10]
Неща, които не трябва да забравяме да настроим:
- [x] Заглавието на портала, да е "Новини и информация - opendata.government.bg".
- [x] Адресът, към който води логото в хедъра.
- [x] #7 
- [x] #6 
- [x] Формат на дата/час, така че да са еднакви с портала

Допълвайте, ако съм пропуснал нещо.

Конфигурация на сайта, след начална инсталация:
WordPress настройки:
- [x] Изключване на коментарите?
- [x] Статична начална страница - нова страница('Начало') с шаблон 'Front'.
- [x] Формат на дата/час, така че да са еднакви с портала (дата: `F m, Y`, час: `G:i`)
- [x] Добавяне на джаджи в страничната лента на главната страница - по преценка какво искаме да има там от наличните (Добавени 'търсене', 'страници' и 'последни публикации'. Могат да бъдат махани и размествани по всяко време - админ панел > външен вид > джаджи).
- [x] Pretty URLs (например, "Дата и име" - `/%year%/%monthnum%/%day%/%postname%/`)

Настройки на темата(opendata-wp):
- [x] Адресът, към който води логото в хедъра
- [x] Мобилното меню - Offcanvas, вместо topbar.

Настройки за сигурност. Ползваме основно безплатното разширение [iThemes Security](https://wordpress.org/plugins/better-wp-security/), което с времето се е показало като едно от водещите в насока обезопасяване на WordPress инсталации. Следват приложените настройки:
**Тук описвам само настройките, които се променят от състоянието им по подразбиране.**

> Global Settings:
- [x] Send digest Email - активирани известия за открити атаки на базата на блокирани IP адреси при опити за разбиване на потребителски пароли или сканиране на сайта за определен софтуер на него.
- [x] Hide security menu in admin bar - оптимизиране на административната лента с премахването на бутона за настройките на сигурност.

> 404 Detection:
- [x] Просто се включва със стандартни настройки.

> Local Brute force protection:
- [x] Minutes to Remember Bad Login (check period) - от 5 на 10min. 
- [x] Automatically ban "admin" user - checked (никой няма причина да ползва такъв user, с добри намерения)

> Database backups:
> __Пускам го, въпреки че имаме наше си бекъп решение - повече бекъпи не вредят, винаги може да се забрави ръчен. ___
- [x] Backup Method - Save locally only - няма нужда да се спами при всеки бекъп.
- [x] Backups to Retain - 5
- [x] Enable scheduled backups - checked
- [x] Backup Interval - 7 days

> System Tweaks
- [x] Protect System Files - спиране на директния достъп по http до файлове, които биха издали информация за сайта, която не е нужна на посетителите. Ако файловете readme.html, readme.txt, wp-config.php, install.php, wp-includes, и .htaccess продължат да са достъпни под някаква форма, ще бъде нужно да им се премахнат правата за четене през командния ред.
- [x] Disable directory browsing - забрана за директен достъп до директории, в които липсва индексен файл (примерно http://example.com/wp-content/uploads/2016/07/)
- [x]  Filter Request Methods - забрана за обработване на trace, delete, или track заявки;
- [x] Filter Suspicious Query Strings in the URL - блокиране на заявки, които наподобяват популярни експлоатации на уязвимости (примерно опити за откриване и експлоатиране на timthumb библиотеката);
- [x] Disable PHP in Uploads - забрана за изпълнение на PHP файлове в папката с качваните от потребителите файлове;

> WordPress Tweaks
- [x] Remove the Windows Live Writer header. - checked (Освен ако някой не ползва windows live writer)
- [x] Reduce comment spam - checked
- [x] XML-RPC - Disable pingbacks
- [x] Disable Extra User Archives - checked

**Comment by mitio** [comment]
@svinqvmraka Имате ли много неща, които остават да се направят преди да е окей да го качим на production? Ако смяташ, че ще е по-лесно да се довършат дреболиите в production, кажи, веднага го качваме. Все още няма да слагаме бутона "Новини и информация" в самия портал и сайтът ще стои скрит, докато не сме готови.

Доколкото знам, смяната на домейна трябва да се направи с някакви updates в базата и не е съвсем тривиална конфигурационна опция. Вероятно всичко останало можем да го нарпавим с един backup/restore/deploy скрипт, който така или иначе е добре да напишем.

**Comment by svinqvmraka** [comment]
Не, никак не са много нещата, преди deploy, даже си мисля че можем още утре да го направим. Има да се донаправят някакви довършителни неща по сигурността и след това можем да го опаковаме и да го метнем на production. Утре сутринта ще обсъдим с @vlood някакви подробности около цялата маневра и ще мога да споделя нещо по-конкретно.

**Comment by mitio** [comment]
FYI @svinqvmraka @vlood сайтът е качен! Намира се на `info.opendata.government.bg`, но DNS-ът още не е готов. Ако искате да го прегледате, насочете към `212.122.185.217`. Ако искате потребител, за да направите настройки, кажете. В момента аз настройвам каквото мога и като е готов DNS-ът, ще дам данни за достъп и на хората от МС и започват да си го пълнят със съдържание вече).

**Comment by svinqvmraka** [comment]
Супер! Да, може да направиш по един акаунт с имена `emo` и `vlood`, да направим нещата възможно най-бързо.

**Comment by mitio** [comment]
@svinqvmraka готово, добавих теб и @vlood, но с малко по-официални имена. Давайте.

Само една мобла имам – добавяйте в този списък тук всяка конфигурация, която правите, за да имаме пълен списък на неща, които е добре да се направят след инсталация на чисто.

Ако можеш, направо с редакция на моя оригинален пост, ако не - в един коментар.

**Comment by svinqvmraka** [comment]
Потвърждавам че имам акаунт и успявам да се логна.

За промените ще редактирам оригиналния пост.

**Comment by svinqvmraka** [comment]
@mitio, направена е началната конфигурация, описани са нещата в първия коментар. По-важното нещо - за да влезнат секюрити настройките трябва да се рестартира nginx-а.

**Comment by mitio** [comment]
Рестартирах.

Може ли да напишеш вкратце какво е това iThemes security? Получих имейли от там за регистрация и API keys. Платена/безплатна услуга ли е, на моя личен имейл ли е (на който получих въпросните имейли), как работят повечето неща, които прави?

Също така, как работят тези и какво значи "checked"?
- Protect System Files - checked
- Disable directory browsing - checked
- Filter Request Methods - checked
- Filter Suspicious Query Strings in the URL - checked
- Disable PHP in Uploads - checked

За последното съм сигурен, че бях сложил ръчно и Nginx правило.

**Comment by mitio** [comment]
P.S. Добавих и "красиви" URL-и, по дата и име. Ако се сещате за възможни проблеми с това, споделете.

**Comment by vlood** [comment]
Залавям се да доопиша нещата по сигурността. Нарочно Емо не беше твърде описателен, за да не пише излишни детайли - аз ще добавя нещата, за които си питал. Няма проблеми с URL-тата, правилно си направил, че си ги пуснал.

**Comment by svinqvmraka** [comment]
В допълнение, @mitio, iThemes security e разширението за сигурност(най-читавото от многото такива налични за WP), което използваме. Основната част от него няма нужда от акаунти, ключове и тн, това което има обаче е една конкретна функционалност, наречена 'Network Brute force protection'.

Понеже съм активирал въпросната функция, автоматично се генерира API key-а(безплатен), който е нужен и се изпраща към мейла на администратора(твоя имейл в случая). Всичко е сетъпнато и не е нужно да се прави нещо допълнително. Спрял съм и разни security newsletter неща и подобни, така че да няма излишен спам. 

Накратко, функционалността, за която говорим прави следното:
Обикновения brute force protection на разширението блокира потребители/хостове при определен брой опити за логин, за определено време(и след определен брой блокирания, ги банва тотално). Network частта от работата блокира IP-та, които са били блокирани от други сайтове, които ползват същата услуга.

**Comment by mitio** [comment]
Как работят въпросните блокировки на потребители, request методи и прочее? На ниво PHP? За какво беше нужно да рестартирам Nginx-а?

А тези стъпки в описанието на issue-то май ще трябва да си сложим в един guide или в `install/README.md`.

**Comment by vlood** [comment]
Временния lockout на потребители се случва по IP адрес но в базата данни, демек на ниво уеб-приложение. Request методите са правила в htaccess, когато работим с Apache, a когато сме с nginx - nginx.conf, където отиват и постоянните забрани за достъп на IP адреси след няколко временни блокирания. Самото разширение за сигурност си изисква рестартиране след първоначалните настройки, предполагам че някое от правилата за филтриране на заявките изисква рестарт, за да влезе в обръщение.

Ще въведа дребна корекция в описанието, след което можем да преместим текста в някой от наръчниците.

**Comment by mitio** [comment]
Виждам, че това е добавено към `install/README.md`, така че считам въпроса за приключен.

P.S. Направих малки редакции на форматирането там.
