### ISSUE TITLE
Превеждане на пропуснати текстове

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#12]
Ето няколко текста, които забелязах, че не са преведени:
- "Search" placeholder-ът в полето за търсене в хедъра.
- "Search" placeholder-ът и бутона в търсачката в лявото меню.
- Страниците за търсене и 404.

**Comment by svinqvmraka** [comment]
Накрая ще преведа всички низове от темата, включително тези по-горе. Ще си бъдат в .po и .mo файлчета, които ще кача тук.

**Comment by svinqvmraka** [comment]
Всички преводи ги има вече, ако добавяме нови низове, ще ги превеждам на крак.
Ако все пак някой забележи нещо, което не е преведено, а трябва, да сигнализира.
Затварям засега.
