### ISSUE TITLE
Прецизиране на размера на шрифтовете в хедъра

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#14]
Казахме, че не гоним pixel-perfect matching на дизайна с този на портала за отворени данни и това все още е валидно, но шрифтовете в хедъра се изрисуват по видимо различен начин на двете места:

Портал:

<img width="985" alt="screenshot 2016-06-29 17 47 12" src="https://cloud.githubusercontent.com/assets/129307/16456720/8d8ad26e-3e21-11e6-887a-3ab2172b7c77.png">

CMS:

<img width="980" alt="screenshot 2016-06-29 17 47 19" src="https://cloud.githubusercontent.com/assets/129307/16456722/8fa75cca-3e21-11e6-9c32-4bdab1619774.png">

Приемам предложения дали лесно можем да направим нещо, така че да сближим двете визии още малко.

Неща, които на мен ми хрумват след бърза проверка:
- `font-weight: 900;` вместо `bold` на почернената част от заглавния текст в хедъра.
- Донагласяне на `line-height`, `font-size`, може би и `font-weight` или опциите за изчертаване и antialiasing.

Виждам, че почти навсякъде се ползва `rem`. Този `rem` стъпва на размера на шрифта на `<html>`, ако не се лъжа. Там е зададено `110%`. Това променя ли се някога, при някакви условия? Дали не е по-добре да се стъпи на фиксиран размер на шрифта в `<html>`, който да бъде увеличаван/намаляван с media queries, в зависимост от размера на екрана?

**Comment by svinqvmraka** [comment]
Agreed и за двете неща:
Когато правих хедъра, още не бях сложил Data Gov шрифтовете и не знаех какъв им е случая(че на font-weight: 700 и 900 се зареждат различните фейсове), та затова е просто strong там. Лесно ще го оправим това.

размерите: 110-те процента не са перманенти, а са толкова докато разуча как точно се случват нещата, така че да съм сигурен че със стойност, която не е в '%', няма да счупя стандартна foundation функционалност. Реално по подразбиране въпросния размер е 100%, което в стандартните браузъри е 16px, като уважава юзърски настройки и зуум. В портала, доколкото видях, base размера е 18px. Та да, това ще го оправя, просто искам да попрочета още малко инфо по въпроса.

Освен тези работи, със някакви малки промени по марджините наоколо, мисля че ще го направим същия.

**Comment by svinqvmraka** [comment]
Update: С размерите няма никаква драма, сетнат е на 18px, както си трябва, като кача следващия ъпдейт на темата тази вечер, ще се оправи и на стейджинга, заедно с останалите проблеми по хедъра.

**Comment by svinqvmraka** [comment]
Имам някакъв напредък с визията на хедъра, утре ще си поиграя още малко с него, за да е максимално идентичен с оригинала.

**Comment by svinqvmraka** [comment]
Мисля че хедъра е максимално идентичен с портала, доколкото е възможно без жертви. Има хоризонтално разминаване, което идва от това че заглавието на сайта и логото са подравнени спрямо ширините на стандартните контейнери на сайта(aside/content), които макар и подобни и на двете места(3/12 и 9/12), в портала са с абсолютни ширини в пиксели, докато в новата тема - в проценти. Не е невъзможно да ги направим в пиксели и при нас, но ще е на цената на читав responsiveness и ми се иска да не го правим. 

Оставям issue-то отворено ако все пак някой смята че приликата не е достатъчна, да мислим още варианти.

**Comment by mitio** [comment]
Смятам, че е достатъчно близо визуално. Съгласен съм със съображенията ти и не бих жертвал и аз responsiveness. Считам въпроса за приключен 👏 👏 👏
