### ISSUE TITLE
Примерна конфигурация за Nginx

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#15]
Във връзка с нуждата да засилим сигурността на админ-частта и това изискване от заданието:

> - Трябва да има ограничение на достъпа до административния панел само за определени IP адреси, като това ще се реализира на ниво Nginx конфигурация.

Вероятно ще стъпим на предложените от Automattic неща [тук](https://codex.wordpress.org/Nginx) и [тук](https://codex.wordpress.org/Brute_Force_Attacks).

**Comment by svinqvmraka** [comment]
В момента се занимавам с блокирането на админа по IP, така че да няма странични ефекти, ще сигнализирам като съм готов.

**Comment by svinqvmraka** [comment]
Имаме вече решение за ограниченията по IP към дашборда на WordPress:
[`029239d`](https://github.com/governmentbg/opendata-cms/commit/ab5d504cc63913371a3d1d479c7af3cedfa095ae).
Как се използва и какво се случва:

Най-отгоре във файла има един map {}. В него изброяваме IP-тата, които искаме да имат различен от нормалния достъп, както и default достъпа до /wp-admin, за всички останали IP-та.

С цел да няма гафове, съм сложил `default 1` ([/install/nginx.conf.example:8](https://github.com/governmentbg/opendata-cms/blob/master/install/nginx.conf.example)), което реално изключва рестрикциите и дава достъп до wp-admin на всички. 

За да заработи нещото, в map-a се добавят IP-та във формат `x.x.x.x 1`. Цифричката накрая може да бъде `1`\- позволява достъп от конкретното IP, или `0` - забранява достъп от конкретното IP. В нашия случай искаме default достъпа да е забранен т.е `default 0;` и определени IP-та да минават, напр.  `185.117.82.20 1;`

Кодът, който реално прави проверките на адресwите и забранява, позволява достъп се намира на ред 37 до 50. Това е метода, който успях да подкарам reliably, без да създава някакви драми, но не претендирам кой знае какви умения с nginx, така че ако някой се сеща за по-добър начин, да свирка.

**Comment by mitio** [comment]
Ако разбирам правилно, въпросната рестрикция пази единствено URL-и, които `~ ^/wp-login\.php`?

Ако е така, нямаше ли да е по-лесно и просто да имаме следната схема:

```
location ~ ^/wp-login\.php {
    include _whitelisted_ip_addresses_for_admin_access.conf;
}
```

И да имаме един такъв файл, в който да има само:

```
allow 127.0.0.1;
allow ...;

deny all;
```

Може даже по подразбиране да няма нищо вътре, да е празен файл, за да работи "по подразбиране".

Така и така има да се редактира Nginx конфигурация, това с отделния файл и allow/deny директивите ми се струва като много по-семпло решение.

Като човек, който е прекарал доста време да обмисля проблема, смяташ ли, че това ще свърши работа и че е по-семпло за управление, или аз пропускам нещо?

**Comment by svinqvmraka** [comment]
Да, абсолютно, това беше първоначалната идея, само че така и не успях да го накарам да работи както се очаква, без да се опитва да свали wp-login.php. Много вероятно е аз да пропускам нещо.
Ще си поиграя пак с това, с отделен whitelist файл ще е по-гот.

**Comment by mitio** [comment]
Това, че го дава за сваляне не е супер фатално (предполагам не показва кода?)

Тествай го с `curl -v` и виж какво вади. Ако те устройва върнатото съдържание и хедъри, сме окей. Виж и дали не е нещо в твоя локален Nginx, където тестваш ти.

**Comment by svinqvmraka** [comment]
Имах предвид, че при IP-тата, от които се предполага че трябва да има достъп, вместо да изпълни wp-login.php(и съответно да покаже логин страницата), ти сервира файла за сваляне(все едно ctrl+S), заедно с цялото съдържание на wp-login.php файла(не че има кой знае какво в него, ама не е гот) ако си го свалиш. Та, при това положение не е използваем сайта, тоест не можеш да достъпиш логин страницата. 

При адреси, които нямат достъп си се вижда 403 на wp-admin/, както си му е редът. Сигурен съм че е глупава настройка в location блока, или комбинация от такива, но не ми се получава за съжаление. В момента си играя с това, ще си кажа ако имам някакъв резултат.

**Comment by mitio** [comment]
А, да, ясно. Мисля, че се сещам как може да се оправи - може би трябва и там да се включат FastCGI директивите, защото ако match-не този location, край, не се ходи до другия, който хваща *.php.

Общият код за активиране на PHP е добре също да се извади в partial.

**Comment by svinqvmraka** [comment]
Случи се работата, много благодаря за разяснението, и сори че съм малко бавен с nginx нещата. Остава ми да изкарам списъка с IP-та в отделен файл и после и съдържанието на `location ~ \.php$ {` блока (ако те разбирам правилно). 
Така `location ~ ^/wp-login\.php {` накрая ще съдържа само два include-а.

**Comment by svinqvmraka** [comment]
[`d897ac7` ](https://github.com/governmentbg/opendata-cms/commit/03cd957efb254463d896a55cc03fe0f099042497) _(не reference-нах issue-то както трябва в комита.._)

@mitio Нещо такова ли имаше предвид? FastCGI директивите, заедно с whitelist-а са изкарани в отделни файлове, и са инклуднати в примерната конфигурация. 

Не съм сигурен дали името nginx.config.example не е малко подвеждащо, предвид че(мисля) тази конфигурация трябва да е във отделен файл `/sites-available/wordpress` и `/sites-enabled/wordpress`, а не да замества nginx.conf. От друга страна, име като `wordpress.example` не е кой-знае колко описателно. От трета - това ще е описано в документацията.

**Comment by mitio** [comment]
Да, това имах предвид, така ми изглежда добре.

Относно по-добрата организация на файловете ми идва следната възможност наум:

Да имаме `install/nginx/opendata-cms.conf`, който да съдържа само конфигурацията на сайта, както и `install/nginx/nginx.conf.example`, който да `include`-ва `opendata-cms.conf`. Който иска, после, ще си го сложи в `conf.d` или `sites-available`/`enabled`. В `install/nginx` могат да са и другите partials и да не са `.example`. Даже се колебая дали и `nginx.conf` трябва да е `.example`, понеже то всичко в тази папка може да се променя от потребителя както си иска, както и би трябвало да може да работи out of the box, ако се изсипе върху някоя Nginx инсталация.

**Comment by svinqvmraka** [comment]
@mitio: Въпрос - гледам реда от стария nginx.conf.example:
`server_name .info.opendata.obshtestvo.bg .wordpress.opendata.obshtestvo.bg;`
Не е ли по-смислено във хранилището да е просто `localhost`, или има някаква друга идея?

Друго нещо, което може би ще е проблем е, че ако искаме да правим include на `opendata-cms.conf` във `nginx.conf`, ще трябва да закоментираме include-а на `/sites-enabled/*`, защото там по подразбиране има файл `default`, който на практика е почти същия като нашия `opendata-cms.conf` и ако ги викаме и двата предполагам че ще се счупи нещо. Може би е по-добре просто да оставим `opendata-cms.conf` в директорията, пък който иска да си го сложи в `sites-available / enabled`?

> би трябвало да може да работи out of the box, ако се изсипе върху някоя Nginx инсталация.

Представям си че поне root директорията ще трябва да се промени, тоест няма да е съвсем out of the box.

**Comment by mitio** [comment]
Да, прав си, по-добре е да е само `localhost` в примера.

Съгласен съм и с всички други твои коментари. Може и да няма `nginx.conf`, ако няма нещо по-специфично там. Webroot-ът може да е `/var/www/opendata-cms` или `/path/to/opendata-cms`.

**Comment by svinqvmraka** [comment]
Тук май сме готови, освен ако не пропускам нещо. 
Създадох [`nginx`](https://github.com/governmentbg/opendata-cms/tree/master/install/nginx) директория и метнах всичките неща там. nginx.conf няма, защото не се сещам за нещо, което да има нужда да слагаме в него.

**Comment by mitio** [comment]
Да, мисля, че всичко е супер. 👍
