### ISSUE TITLE
Credits в дъното на сайта (footer)

### ISSUE THREAD

**Issue by vlood** [governmentbg/opendata-cms#16]
Какво да пишем в дъното на сайта - копираме го както е в opendata, или сменяме ckan с WordPress?
Падащото меню "Език" въобще да не го правим, или да го оставим, пък макар и само с български?

**Comment by mitio** [comment]
Не е добре да го копираме едно към едно, защото:
- Менюто за езика няма да работи.
- Линкът към API-то се променя с различните версии на CKAN.
- CMS частта не е CKAN.

Предлагам да сглобим футър, който да има линкове към началната страница на портала (може би към същото, накъдето води и логото), линк "За портала", информация, че тази част се задвижва от WordPress и че кодът на CMS частта може да бъде намерен тук и тук и се разпространява под лиценз Х (GPLv3?). Махаме частта "изработено от..." Може би може да се дублира менюто от хедъра и да сложим под него изречението за WordPress и лиценз. Отворен съм към предложения там да има каквото ви се струва смислено и удобно за потребителите като информация.

**Comment by svinqvmraka** [comment]
Това, което си мислех е да добавим ново меню за линковете от лявата му част, така че да могат да се редактират лесно и независимо от главното меню, а от дясно просто 'задвижван от WordPress'  с WP логото, подобно на това на ckan  в момента. Ще е подобно на сегашното като визия и в същото време няма да има невярна информация в него.

**Comment by mitio** [comment]
Звучи добре.

Аз бих сложил и линк към хранилището с кода. По ваша преценка.

**Comment by svinqvmraka** [comment]
Сложих меню('footer-menu') от лявата част на футъра, а от дясно WP и github информацията. Ако имате идеи какво да напишем, така че да е по-подредено и смислено - стреляйте. Не знам дали го споменах някъде другаде - менютата се управляват от 'външен вид -> менюта', като името на футър менюто е 'footer menu'(колко оригинално), името на локацията е същото. 

сложил съм някакви примерни линкове, докато измислим какво искаме да има от лявата страна.

**Comment by mitio** [comment]
Струва ми се, че сега има твърде много излишна и дублираща се информация, а логата са ми много големи и неконсистентни едно с друго.

Предлагам да опростим нещата и да направим така:
1. Да махнем footer менюто.
2. Да сложим следния центриран текст:
   
   > Секция "Новини и информация" е част от [Портала за отворени данни на Република България](http://opendata.government.bg/). Задвижва се от [WordPress](https://wordpress.org/) и е с отворен код, [достъпен в GitHub](https://github.com/governmentbg/opendata-cms) и лицензиран под [GPLv3](https://github.com/governmentbg/opendata-cms/blob/master/LICENSE). Ако забележите проблем или имате предложение, [сигнализирайте](https://github.com/governmentbg/opendata-cms/issues/new).

Ако ще слагаме визуални иконки, може да са малки пиктограми, които да са вмъкнати inline до думите "WordPress" и "GitHub" (съответните им лога). Иначе може и без тях.

Няма какво да се изхвърляме с излишни сложности.

**Comment by svinqvmraka** [comment]
Опростеният футър е вече качен на стейджинга.
