### ISSUE TITLE
Единични публикации и страници

### ISSUE THREAD

**Issue by svinqvmraka** [governmentbg/opendata-cms#17]
Тук предлагам да изговорим какво искаме да има в единичните публикации(_single post_) и единичните страници(_single page_).

Някакви въпроси, които ми изникват, ще добавям още ако се появят:
- Под заглавието на публикациите има post meta - дата на публикуване и автор. Авторите ми се струва излишно да се показват, закоментирал съм ги за момента, ако прецените че има нужда от тях може да ги върнем.
- По подразбиране има възможност за коментиране по публикации и страници. Има вариант да се изключат по подразбиране и да се пускат само на отделни публикации/страници, или обратното - да ги има по подразбиране и да се изключват в частни случаи.
- [Единичните страници в портала](http://opendata.government.bg/about) нямат сайдбар и се разполагат на цялата ширина на сайта (940px). В момента публикациите и страниците в WordPress имат сайдбар от ляво, подобно на заглавната страница. Махането му е тривиално, просто трябва да се реши дали го искаме. Аз лично мисля че отнема фокуса от същинското съдържание и бих го разкарал.

**Comment by mitio** [comment]
Да, по-добре е, че си скрил автора. Датата е добре да я има.

За коментарите, моето мнение е, че е по-добре по подразбиране да са спрени. Даже може би е добре като са спрени, да не излиза нищо за коментарите (т.е. да не пише "Коментарите са спрени").

Въпреки това, нека @Glamdring си каже позицията.

**Comment by svinqvmraka** [comment]
Само да потвърдя че когато са изключени, няма съобщения "Коментарите са изключени" и подобни, просто не се показват.

**Comment by Glamdring** [comment]
- за авторите, ок да ги няма
- засега без коментар, и както каза Митьо - без "коментарите са спрени"
- окей без сайдбар

**Comment by svinqvmraka** [comment]
- авторите вече ги няма в публикациите, само дати. 
- Коментарите са изключени глобално, като за отделни страници или публикации могат да се включат с една отметна през страницата за редактиране.
- Сайдбарът е махнат от единичните страници(но го има навсякъде другаде.) 

Затварям, ако има нещо свиркайте.
