### ISSUE TITLE
Скъсяване на placeholder-а на sidebar полето за търсене или друго дизайн решение

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#18]
В момента placeholder-ът на полето за търсене, което е в лявата лента, е твърде дълго и не се побира:

<img width="245" alt="screenshot 2016-07-04 12 16 15" src="https://cloud.githubusercontent.com/assets/129307/16556275/c4595306-41e1-11e6-8e23-171782f05995.png">

Аз промених заглавието на джаджата на "Търсене в новини и информация". Идват ми наум следните решения:
- Да сменим текста на полето за търсене на "Ключови думи…", "Търсене…" или друго по-кратко.
- Да потърсим друго визуално решение.

**Comment by svinqvmraka** [comment]
Решението ми беше да намаля размера на текста малко и да сложа падинг в дясно под иконката, така че да е сигурно че няма да минава отдолу. Не е качено още на стейджинга, но е commit-нато като код от преди час-два.

Но да, може би по-доброто решение е самата джаджа да се казва 'Търсене в новини и информация' пък placeholdera да си е просто 'Търсене'. 

Ето и как биха изглеждали двата варианта:
![2](https://cloud.githubusercontent.com/assets/3404749/16556684/160327f2-41e4-11e6-8d51-4ca7b1c9a84b.png)
или
![default](https://cloud.githubusercontent.com/assets/3404749/16556683/1601790c-41e4-11e6-85b4-12a7859dd4c7.png)

Мисля че първия вариант е по-смислен. Ако няма различни мнения, при следващия ъпдейт на темата ще променя placeholder-а обратно на 'Търсене'.

**Comment by mitio** [comment]
Харесва ми текущото ти решение, с "Търсене" като placeholder. We're good.
