### ISSUE TITLE
Използване на същия шрифт като opendata сайта

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#2]
Мисля, че е важно за визуалната консистентност между двата.

**Comment by svinqvmraka** [comment]
Съгласен, вече е направено, малко по-късно днес ще кача промените на staging-a.

**Comment by mitio** [comment]
Супер, като ги качиш, може да затвориш това issue.

**Comment by svinqvmraka** [comment]
Готово, ползваме Data Gov шрифта вече. Затварям.
