### ISSUE TITLE
Допълване на секцията за създаване на нов release в README-то

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#20]
Във връзка с 28d82fe453e124df3d3de51ced316ef9b3a5f59e. Това, което съм написал, е по-скоро  placeholder. Представям си кратки инструкции, които всеки, който има достъп до това хранилище, да може да изпълни, ако му се наложи да направи промяна в CSS, HTML или нещо друго по темата.

**Comment by svinqvmraka** [comment]
Написах кратък списък с нужните неща, така че да може всеки с достъп дa започне да работи по темата на локална среда.

Затварям за момента, ако не се разбира нещо, отваряйте пак.
[`f6dd4b6`](https://github.com/governmentbg/opendata-cms/commit/f6dd4b6731c20e440b23d1f63649da81ef4f4e41)
