### ISSUE TITLE
Скриване на активния елемент от менюто в мобилната версия

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#22]
В момента основното навигационно меню реално не се ползва и е само за визуална "съвместимост" с портала.

В мобилната версия нещата изглеждат така заради вечно активния елемент от менюто:

![screenshot 2016-07-21 20 05 32](https://cloud.githubusercontent.com/assets/129307/17031792/8d533be2-4f7e-11e6-8af2-501d1f2113f9.png)

Мисля, че е добре да го скрием, тъй като под менюто си има breadcrumbs, указващи ясно в коя секция се намира потребителят.

**Comment by svinqvmraka** [comment]
Активния линк в менюто няма нищо общо с този текст. Във тъмната лента се показва заглавието на сайта, в което в момента е въведено 'Новини и информация - opendata.government.bg'. Ще го махна от там, заедно с цялата черна лента - не виждам смисъл от нея.

**Comment by mitio** [comment]
Качих 1.0.1 на production и черната лента + заглавието са вече скрити, но мисля, че се е отворил друг проблем:

![screenshot 2016-07-22 15 16 02](https://cloud.githubusercontent.com/assets/129307/17056891/4748463c-501f-11e6-9e50-81a855561ca2.png)

Някаква идея защо?

**Comment by svinqvmraka** [comment]
При инсталирането на новата тема през админ панела обичайно се налага да се изтрие старата, което ѝ затрива настройките. В момента просто показва мобилното меню по подразбиране и трябва да се цъкне 'offcanvas' през 'Външен вид > настройки > mobile menu'. Сега ще го направя.
Проблемът може да се избегне ако просто се разархивира темата и се копира върху старата във wp-content/themes/

**Comment by mitio** [comment]
Хмм... Аз я "обновявам" през install скрипта.

Има ли начин да запазваме настройките на темата при такова обновяване? Не искам да се занимаваме с ръчни разархивирания, или пък да имаме дублиращи се инсталационно-деплой скриптове.

**Comment by mitio** [comment]
P.S. Обновявам с тази команда: `./install/install.sh /var/www/opendata-cms/`

**Comment by mitio** [comment]
Ще отворя ново issue за това. Този проблем го считам за разрешен 🔨
