### ISSUE TITLE
Инсталационният скрипт да запазва настройките на темата при "update"

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#23]
В идеалния случай, бихме искали да имаме лесен начин да обновяваме темата. Ако това става със скрипт, ще е най-удобно.

В момента, инсталационният скрипт е много близо до това състояние, но се оказва, че не запазва настройките на темата при инсталация на нова версия.

Добре е да помислим за начин това да не се случва.

**Comment by svinqvmraka** [comment]
Явно wp-cli не прави нищо по-различно от изтриване на старата тема + ъплоуд на новата. Причината за това е че стандартния начин по който WordPress се справя със ситуацията '_някой се опитва да инсталира тема с име ''X', обаче вече има такава_' е да каже '_вече има директория със същото име_', което не оставя друг избор, освен да се изтрие темата и да се реъплоудне(което и wp-cli прави).

Мислим по въпроса за по-смислено ъпдейтване.

**Comment by mitio** [comment]
Идват ми наум следните неща:
1. Да се види какви опции има `wp-cli` за тази задача и дали няма някой флаг, който да спаси положението.
2. Да правим това в `install.sh` ние, ръчно, както на другите стъпки – ако засечем, че темата я има вече, да свалим zip-а ние и да направим някакъв unzip.

**Comment by svinqvmraka** [comment]
Да, то това са вариантите, в краен случай просто ще разархивираме в скрипта архива и ще заместваме старата. Искам да разгледам всички варианти преди това, в случай че има някакво по-елегантно решение. Във всеки случай - драмата не е голяма, ще го оправим.

**Comment by svinqvmraka** [comment]
Скрипта вече не затрива настройките на темата. За да се случи това, вече не ползваме `wp theme install` фунционалността на wp-cli, а директно сваляме .zip архива от github releases, разархивираме го върху старата тема, активираме я и след това изтриваме .zip файла.

[Commit 1](https://github.com/governmentbg/opendata-cms/commit/707760f6b5683911a5cadf16c26ea5535e85ba4f)
[Commit 2](https://github.com/governmentbg/opendata-cms/commit/34b33ba5e8bff31cc966addabc71b1d18c042137) - (забравих да изтрия архива, та за това са два)

**Comment by mitio** [comment]
Качих версия 1.0.2, мисля, че нещата работят. 👍
