### ISSUE TITLE
Предложение за подобрение относно секция "Организации"

### ISSUE THREAD

**Issue by EllyTs** [governmentbg/opendata-cms#28]
Здравейте!
Сайтът е прекрасен и много полезен! Поздравления!
Вече е събрана и публикувана доста информация и е организирана много удобно чрез етикети.
Бих предложила подобен подход и за организациите, които са вече над 400 и е доста трудно да се навигираш ако не търсиш нещо конкретно, а просто опознаваш информацията.
Тъй като осъзнавам колко трудно е изграждането на подобна йерархия бих предложила на първо време просто да се отделят общините в отделна секция, тъй като ми направи впечатление, че те, логично, са май-голям брой от организациите.
Ще се радвам да получа обратна връзка дали горният съвет ви е бил полезен.
Поздрави!
Ели

**Comment by mitio** [comment]
@EllyTs Здравейте! Предложението ви е съвсем разумно и даже вече е в списъка с неща, които са планирани: governmentbg/opendata#46 Към момента не можем да дадем гаранции кога ще стане това, но е с висок приоритет в списъка.

Благодарим ви, че сте отделила време да ни предоставите обратна връзка!
