### ISSUE TITLE
Не работеща връзка на ресорсите от търговски регистър 

### ISSUE THREAD

**Issue by arjanvaneersel** [governmentbg/opendata-cms#29]
На страниците на ресорсите с данните от търговски регистър има не работеща връзка за за зип файл със схемата: http://www.registryagency.bg/media/filer_public/f6/4e/f64e4dda-ec2d-4b09-a130-eb13979b4882/schemas.zip

**Comment by Glamdring** [comment]
Линкът е коригиран
