### ISSUE TITLE
Да сложим footer?

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#3]
Мисля си за нещо, което дублира и наподобява футъра на портала, дори да не е едно към едно.

**Comment by vlood** [comment]
Явно съм пропуснал да го спомена като нещо, което още не сме направили - не е забравен футърът, ще бъде като на портала.

**Comment by mitio** [comment]
Нищо, аз описвам каквото видя, за да не забарвя. Като се сложат нещата, просто ще затворим тези issues.

**Comment by mitio** [comment]
Решено е – ще има footer. Дискусията какво точно да има там, е в #16.
