### ISSUE TITLE
Насочване на логото към http://opendata.government.bg

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#4]
Повечето хора очакват като кликнат на логото, да отидат в началото на сайта. Тъй като WordPress е по-скоро имплементационен детайл тук, считаме, че началото на сайта е началната страница на портала за отворени данни. Струва ми се добра идея логото да води натам.

В контекста на това, не знам дали е възможно темата да има някаква ясно изнезена конфигурация, където да стоят неща като този URL. Това е страничен въпрос, обаче.

**Comment by vlood** [comment]
Настройка на темата, достъпна през стандартния WordPress Customizer за указване на адреса на логото как ти звучи? На мен това ми се струва най-праволинейното решение.

**Comment by mitio** [comment]
Да, ако е настройка, звучи добре. Ще оставя това issue отворено, докато не deploy-нем, за да не забравим да го направим.

**Comment by svinqvmraka** [comment]
Добавена е нова секция в customizer-а, с поле за URL. Намира се във `Външен вид >> настройки >> header settings(ще го преведем заедно с останалите неща накрая)`, когато нашата тема е активна. Там има текстово поле, в което се въвежда адресът, към който ще сочи логото. Ако полето е празно, ще сочи към начaлната страница на WordPress сайта.
