### ISSUE TITLE
Добавяне на бутон "Новини и информация" (винаги активен)

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#6]
В опит да направим този CMS компонент да изглежда повече като интегрална част от портала, предлагам да сложим бутон в хедъра "Новини и информация" (да кажем след "Визуализации"), който да свети като активен (с керемиденочервения фон от портала), все едно сме в тази секция от портала.

**Comment by svinqvmraka** [comment]
Писах в #7, но и тук да го спомена - просто се добавя нов custom link през WP интерфейса и му се слага 'active' клас(има си поленце за custo css class). Добавям го на стейджинга. Нека си седи issue-то, че да не го забравим накрая на истинската среда.

**Comment by mitio** [comment]
Това е направено, споменато е и в #10, затова го затварям.
