### ISSUE TITLE
Насочване на елементите от менюто към съответните URL-и от портала

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#7]
Не съм сигурен как се прави това. Ако е в темата, трябва да го сложим там. Ако е настройка (както за логото в #4), тогава ще го направим при deploy.

**Comment by svinqvmraka** [comment]
Менютата се правят през drag&drop интерфейса за редактиране на менюта на WordPress(админ панел >> Външен вид >> Менюта), от където реално просто трябва да добавим нов линк и да му сложим клас 'active'. Може да се направи по всяко време и отнема минутка.

**Comment by mitio** [comment]
Това е направено и е вече нерелевантно, заради #10.
