### ISSUE TITLE
Скриптове за автоматизиран бекъп и deploy

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#8]
Както сме коментирали вече в [това issue](https://github.com/governmentbg/opendata/issues/44#issuecomment-222365569).

Може би [скриптовете в това хранилище](https://github.com/openmediabg/openmedia.bg/tree/master/bin) могат да са полезна отправна точка.

**Comment by vlood** [comment]
Все още работим по скриптовете за backup, restore & deploy, но междувременно можем да създадем пакет на сайта с разширение, който да се инсталира с уеб-интерфейс директно на живата среда, така че да не задържаме колегите от министерството. Кажете дали това би ви вършило работа временно, че да хващаме да го пакетираме направо.

**Comment by mitio** [comment]
Ако от това няма да има нужда в бъдеще и ще е само за да качим нещата
по-бързо, няма нужда да го правим. Не е толкова спешно да го качим. Като
сме готови.

**Comment by vlood** [comment]
Бързо е, но няма да има нужда от него в бъдеще. Ще пиша пак, когато сме готови с решението.

**Comment by vlood** [comment]
Имаме работещ скрипт за архивиране на базата данни и файловете, мята ги директно в home директорията, като имената им съдържат датата и времето на създаване на архива. Ползва се WP-CLI, понеже същото ще е нужно и при deploy скрипта, пък по този начин избягваме нуждата от писане на паролата за базата в самия скрипт или допълнителен конфигурационен файл. Скоро ще бъде качен в репото.

Вече е качен скрипт за deployment, който обаче изисква да същестува staging и жива среда с инсталиран WordPress, за да може да работи.

Работим по скрипт, който да прави чиста WordPress инсталация с нужните разширения и актуален код от темата, генерирайки стиловете и всичко останало, което идва от Foundation. Същият отново ще зависи на WP-CLI, а @svinqvmraka може да каже, ако има още нещо, което пропускам.

**Comment by mitio** [comment]
Звучи ми супер!

Пингнете ме, като сте готови да качваме на production, или просто ми оставете груби инструкции, за да кача нещата аз.

**Comment by svinqvmraka** [comment]
Имаме почти изцяло работещ install скрипт. намира се в opendata-cms/wp-cli-deploy/install.sh, като преди да се изпълни трябва да му се попълни кратката конфигурация(няколко промениливи в началото на файла - име на база, потребители, пароли и тн). След като това е готово, скрипта ще свали последната версия на WordPress във директорията в която е клонирано репото(./../../), ще създаде wp-config.php файл и ще инсталира WordPress в същата тая директория. След това ще копира wp-content(която съдържа плъгини, теми и качени файлове) директорията от репото към новоинсталирания WordPress.

Това, което все още не прави, а трябва е да build-ва asset-ите на темата - npm install и npm run build(или npm run production - само минифицираните файлове без sourcemaps). В директорията на темата(wp-content/themes/opendata-wp/) все още седи оригиналното readme.md на foundationpress, за повече инфо по въпроса там как работят нещата. 

След това следва писането на цялата документация както трябва и на български. 

Deploy скрипта на теория работи, но трябва да го тестваме още, така че да се изчистят някои проблеми и да може да се разчита че винаги работи както трябва.

**Comment by mitio** [comment]
Как вървят нещата? Има ли нещо, с което можем да помогнем?

Като имате идея кога искате да направим пробен деплой, само дайте знак.

**Comment by vlood** [comment]
Срещнахме нелепи драми по тестовете на скрипта заради билдването на темата заради купчина зависимости с Node, заради което днес решихме, че билдването ще се случва само на dev средата, а в хранилището ще държим актуален пакет на билднатата тема и отделно на всички работни файлове на SASS и т.н.

Утре подреджаме хранилището във финална структура, преправяме install & deploy скриптовете, където се налага, пишем guidelines за работа с кода (като се променя по темата, да се билдва и качва новия пакет заедно с кода). Не сме забравили и #1, ама той е отделно, вярвам :)

**Comment by svinqvmraka** [comment]
Инсталационният скрипт работи вече. Нещата, които съм писал за него в предишният ми коментар все още важат, различен е начина по който handle-ваме темата. Описвам го тук, за да са всички в течение, докато се появи документация:

В текущото хранилище има wp-content/themes/opendata-wp/, в която е работната версия на темата(която съответно няма компилирани css/js asset-и и не трябва да се инсталира директно). Вътре има друга папка /packaged-theme/, в която се намира пакетирана, готова за инсталиране на production тема. Инсталационният скрипт копира цялата wp-content/ директория от хранилището към новия сайт и след това инсталира и активира темата от въпросния .zip файл.

Не трябва да се забравя да се попълни информацията в install.sh(име на база, потребители, пароли, адреси и тн), преди да се пусне. 

Работната тема(тази от хранилището тук) е предназначена за dev средите и има нужда от nodejs 4.x.x(и съответно npm) за да си компилира сорса. След клониране на репото, трябва да се пусне 'npm install' в руут-а на темата, и след това вече могат да се ползват `npm run watch`, за да се следят файловете и да се компилират при запазване, или `npm run build`, за да се компилират нещата веднъж. `npm run package` пък ще генерира zip на темата, готов за деплой в ./packaged/ директорията и с име, съдържащо дата/час на генериране.

**Comment by mitio** [comment]
Добре, имам нужда от малко повече информация по въпроса, за да разбера какво се случва и защо.

Първо, ако разбирам правилно, въпросният скрипт служи за инсталация "на чисто", а не за възстановяване на "архив" на сайта? Тоест, всички настройки, които са направени в момента в базата, ще трябва да се направят наново? И в тази връзка, имаме ли план да направим нещо, което автоматизирано да възстанови и архив на базата и качените файлове, след инсталация "на чисто"? Може би с още няколко команди от `wp cli` може да стане това?

Второ, относно zip-а - разбирам, че искаме да разделим build-ването на темата от инсталацията й, заради по-сложния environment, нужен за build-ването. Не разбрах какъв точно е проблемът с този environment и защо взехте това решение, но мисля, че не е зле да ги има разделени.

Имам следните питания в тази връзка:
- Въпросният zip съдържа всичко нужно за инсталация на темата? Ако да, [защо са ни тези редове](https://github.com/governmentbg/opendata-cms/blob/fa0b7b3/wp-cli-deploy/install.sh#L36-L37)?
- Не мислите ли, че е по-добра идея вместо да слагаме zip в Git, да ползваме [GitHub releases](https://help.github.com/articles/about-releases/)? Това [може и да се автоматизира](https://developer.github.com/v3/repos/releases/#create-a-release) в някакъв момент, като в началото може да се прави ръчно – променя се темата в dev, след това нещата се commit-ват, тагват се, build-ва се "артефакт" – въпросният zip – който се качва в GitHub и се ползва за deploy/install. На инсталационния скрипт може би може да му се казва версия, която да инсталира – и готово. Така може и темата да си има proper versioning, който да се появяв коректно в админа. Как ви се струва?
- Струва ми се, че е добра идея конфигурацията на първоначалната инсталация да е извън VCS, като в Git има само един `.example` файл, [както тук](https://github.com/governmentbg/ckan-install/blob/master/config.sh.sample). Инсталационният скрипт се опитва да зареди конфигурация (със `source config.sh`), а ако няма такъв файл, изписва съобщение от типа на "Please copy config.sh.example to config.sh and edit it accordingly before running this installation script."

Зависимостите на install скрипта в момента са (допълнете, ако пропускам нещо):
- MySQL client & server
- PHP с CLI & FPM backends
- Nginx с определени конфигурационни файлове
- Git
- Нещо друго?

Зависимости за създаване на нов build на темата:
- Git
- node & npm
- Какво друго?

Процедурата по build & release трябва да е описана в readme-то като списък от предварителни зависимости и списък от команди, които трябва да се изпълнят и неща, които трябва да се направят, за да се продуцира нов release. Мога и аз да го направя, като ще е добре да погледнете после дали не съм написал нещо грешно. Върви ми да пиша readme-та :)

**Comment by vlood** [comment]
По първия въпрос - покрай историите с деплойването сме пропуснали restore на архива. Никой от сегашните скриптове не върши работа, така че това трябва да го направим. Не мисля, че ще мине само с wp-cli, но при всички положения ще се използва.

По втория въпрос - имахме драми с разминаващи се версии на node модули, че и на самия node. Тук @svinqvmraka може да го обясни по-смислено, предвид че основно той го бори, но реално стигнахме до прозрението, че всъщност като цяло build-ването не бива да се прави в живата среда, а единствено в средата на разработчиците.
- ZIP-ът съдържа всички нужни файлове за темата да бъде инсталирана и използвана от кой да е WordPress сайт. Посочените от теб редове не съм сигурен последно дали не трябваше да са само папката на разширенията с идеята, че в някакъв момент може да има добавяни разширения към проекта и ще е смислено да влизат директно с този скрипт. @svinqvmraka ще каже дали не е пропуснал да качи някакъв код в хранилището.
- GitHub Releases не ми беше хрумвало да ползваме, понеже до момента не съм използвал въпросната функционалност, но всъщност звучи прекрасно. Ще я разровим, за да влезне в употреба в проекта по начина, който предлагаш.
- Конфигурационен файл извън скрипта е уместна забележка, ще бъде направено.

При зависимостите на инсталацията трябва да включим wp-cli. Инсталацията на wp-cli е проста, та бихме могли да я включим в самия скрипт.

Build зависимостите @svinqvmraka ще ги опише, но на мен ми се струва, че нищо не липсва.

В предишния коментар на колегата бе нахвърляна процедурата, като след като изгладим забележките, които ни писа сега, ще разпишем по-подробни инструкции в основния readme файл.

**Comment by mitio** [comment]
Разбирам. Може би проблемите с версиите са били разрешими, но да има отделен build и по-семпъл install/deploy скрипт е нелош вариант, така че добре, че избираме него.

Засега приоритетът ми е до края на тази седмица да направя deploy на production и да покажа нещата на колегите от Министерски съвет, за да започнем работа с тях по съдъражнието. Аз съм напълно окей да направя въпросния деплой ръчно и да донастроя каквото е нужно в production, като ние след това продължим да довършваме тук каквото има за довършване и от време на време качваме нещата live.

Аз ще пробвам да направя въпросния деплой утре или вдругиден, използвайки информацията, която сте споделили вече тук, в issues. Ако се сещате за нещо, което е добре да имам предвид, кажете. Ако не, при удряне на греда, аз ще се обадя :)

А за базата, виждам, че `wp cli` [има както опции за експорт и импорт на базата](https://wp-cli.org/commands/db/), така и [импорт/експорт на неща във WXR](https://wp-cli.org/commands/export/), което може да е по-удачно (или не – не познавам достатъчно WP и не знам дали второто е бекъп на повече неща, вкл. user uploads. Давам го просто като идея, макар че вероятно сте наясно с възможностите там.

**Comment by svinqvmraka** [comment]
> Не разбрах какъв точно е проблемът с този environment и защо взехте това решение [...]

Решихме че няма смисъл, заради нещо подобно, да имаме зависимост от node на production среда, заедно с ~300mb node_modules/ в темата. Правилният build зависи от твърде много неща, които не можем да контролираме(версии на node, npm, произволни проблеми с модули на някаква конкретна среда/kernel), а тези неща ще блокират build-а на всички асети на темата, без които е реално неизползваема. По-сигурният и чист вариант(поне според мен) е да си имаме културно .zip-че с темата, пакетирана и готова, пък който иска може да си билд-не нещата на dev средата, както си му е редът.

> Ако да, защо са ни тези редове?

_Какво правят(мисля че на всички ни е ясно какво правят, но за протокола): Въпросният ред копира рекурсивно съдържанието на `wp-content/` от хранилището(там е само темата в момента) към `wp-content/` директорията на новоинсталирания WordPress._
В момента реално няма нужда от този ред, защото нямаме custom плъгини или нещо различно от темата, което да искаме да се копира. Въпросното нещо е там, само и единствено, за да сме сигурни че набора теми/плъгини/uploads са еднакви между репото и сайта, който скрипта инсталира. Можем да го махнем изцяло без последствия, просто сметнах за добра идея да го има.

> GitHub Releases

Също не съм ползвал въпросното нещо, но ми изглежда супер, утре ще разгледам как ще станат нещата.

> Build зависимостите @svinqvmraka ще ги опише, но на мен ми се струва, че нищо не липсва.
- Node.js (препоръчително 4.х.х, за да се избегнат потенциални проблеми, макар че го тествах с 6.3 без драми), npm-a към него се подразбира;
- Документацията на [FoundationPress](https://github.com/olefredrik/FoundationPress) казва че трябва да имаме 'gcc' пакета, за компилирането на scss файловете, но ако не се лъжа го има в повечето дистрибуции така или иначе. 
- Git - Build-а не зависи от него, така че не би трябвало да е проблем и да го няма.

> Аз ще пробвам да направя въпросния деплой утре или вдругиден, използвайки информацията, която сте споделили вече тук, в issues. Ако се сещате за нещо, което е добре да имам предвид, кажете. Ако не, при удряне на греда, аз ще се обадя :)

Всичко би трябвало да е гладко, ако има проблем всички сме на линия за съдействие. Нещото, което вероятно си струва да се отбележи - още в началното, базовата nginx конфигурация на стейджинга беше направена, предполагам от теб. Сайта работеше, но при опит да отвориш вътрешна страница връщаше 404. Проблема тогава се оказа файла /etc/nginx/sites-available/wordpress на ред 13, който изглеждаше така `try_files $uri $uri/ /index.html;`. За да започне да работи го промених на `try_files $uri $uri/ /index.php?$args;`, както е в документацията на WordPress. Оригиналният файл съм го оставил там с .bak накрая, за да могат да се сравнят промените евентуално.

**Comment by svinqvmraka** [comment]
Инсталационният скрипт вече използва GitHub releases. При създаване на release-а, трябва да се генерира пакет от темата(npm run package - локално) и да се добави като binary. Скрипта гледа първия binary file, от последния release на репото, сваля го и го инсталира/активира. Следва изкарване на конфиуграцията му в отделен файл.

**Comment by mitio** [comment]
Мисля, че сега схемата с инсталацията и releases е доста културна и прилична, поздравления!

Предлагам да махнем копирането на файлове от wp-content от инсталационния скрипт и да се добави чак когато има нужда. В случая ми се струва, че такова redundancy е по-скоро вредно и замърсяващо, при положение, че всичко необходимо за темата го има в .zip-а ѝ.

Ще пробвам деплой тези дни и ще пиша за резултата, или ако има проблем. Няма проблем с базата – или ще я копирам аз едно към едно, или ще сетъпна нещата на чисто. Ще видя. Ако я копирам едно към едно, после ще трябва да изчистим някои работи, но това вероятно ще е лесно.

Благодаря ти за уточнението за Nginx конфигурацията, точно за такива неща имах нужда. Stay tuned.

**Comment by svinqvmraka** [comment]
OK за копирането на wp-content, махаме го.

Колкото до базата и deploy-a като цяло - Deploy скрипта би трябвало да работи безгрижно в момента, а той копира базата заедно с нужните файлове, така че мисля че той ще ти свърши работа. Скрипта иска да се дефинират няколко допълнителни константи във wp-config.php за да знае къде е новия сайт и да има достъп до него и базата му. Малко ни липсва документация в момента, но [това](https://github.com/c10b10/wp-cli-deploy) е скрипта, който се ползва, заедно с оригиналната му документация. С две думи - трябва да има staging и live среди с инсталиран WordPress и на двете. Добавят се константите, описани в линка по-горе във wp-config.php и от там нататък би трябвало скрипта да си върши работата. Скрипта може да прави pull или push, тоест може да се стартира на стейджинга и да качи всичко към production, или обратното - да се изпълни на production средата и да си дръпне нещата от staging-а. Пробвал съм го по първия начин - staging -> live. 
Нужните команди са описани в оригиналното репо, но тази, която ни трябва в случая е `wp deploy push live --what=db && wp deploy push live --what=themes` като 'live' частта от командата зависи от дефинираните константи във wp-config, пример `define( 'LIVE_URL', 'the-remote-website-url.com' );` може да бъде `define( 'DEV_URL', 'the-remote-website-url.com' );` и тогава ще трябва да изпълним `deploy push dev --what=db`. На линия съм по всяко време за съдействие ако има нужда от такова.

Иначе да, има доста тестово съдържание на staging-a, което ще трябва да се изчисти. Реално погледнато дори и да се започне на ново, конфигурацията ни се състои в две елементарни настройки на темата, конфигуриране на разширението за сигурност и настройване на някакви малки подробности, през които така или иначе ще трябва да минем.

**Comment by svinqvmraka** [comment]
Инсталационният скрипт вече си търси install.config файл за конфигурацията, ако го няма мрънка за това и спира. Имаме си и install.config.example, който трябва да се копира като install.config и да му се попълнят няколкото променливи. Също, махнах излишното копиране на wp-content.

**Comment by svinqvmraka** [comment]
Направих леко разтребване на скриптовете в хранилището, защото всичко в една папка мисля че не е много user friendly. Та, по този случай в root-a на репото вече имаме директории `install`, `backup-restore` и `wp-cli-deploy`, съдържащи съответно скриптовете за инсталация, бекъп/рестор и deploy.

Написах и някакво базово readme.md за инсталационният скрипт, обясняващо процедурата с конфигурационния файл, както и зависимости на скрипта и тн. Не претендирам да мога да пиша readme-та, та ако има нещо неясно написано или пропуснато, свиркайте да го оправяме.

**Comment by vlood** [comment]
Изтъркаляхме още няколко теста на backup & restore скриптовете след добавянето на конфигурационен файл, така че нещата би трябвало да се случват както трябва. @mitio, бъди безпощаден в критиката, че да оправяме грешките по-скоро, като попадаш на такива!

**Comment by mitio** [comment]
В момента правя тестове и някои промени по инсталационния скрипт.

В инсталационното readme пише, че скриптът има нужда от PHP 5.6+. Това вярно ли е? Знаете ли за някаква причина да не работи на, да кажем, 5.4+?

**Comment by svinqvmraka** [comment]
Скрипта сам по себе си ще работи с всичко от 5.3, нагоре(според изискванията на wp-cli), но минималната версия на PHP, която е описана в [изискванията](https://wordpress.org/about/requirements/) на WordPress е 5.6, затова и нея съм сложил като изискване.

Аз пък момента правя разни допълнения към бекъп/рестор скриптовете, ще се появят като комити след малко.

**Comment by mitio** [comment]
Да, разбирам, благодаря за линка. Всъщност 5.6+ е recommended, а минимум са:

> Note: If you are in a legacy environment where you only have older PHP or MySQL versions, WordPress also works with PHP 5.2.4+ and MySQL 5.0+, but these versions have reached official End Of Life and as such may expose your site to security vulnerabilities.

Аз направих доста промени по инсталационния скрипт. Качвам ги сега.

**Comment by mitio** [comment]
[Това са моите промени](https://github.com/governmentbg/opendata-cms/compare/28d82fe453e124df3d3de51ced316ef9b3a5f59e...e42c1305874e5d4f69f52ac2fb1812f8e09cb365) по инсталационния скрипт.

Мисля, че така е по-удобен и даже става и за deploy скрипт.

Сега ще го тествам на production :)

**Comment by svinqvmraka** [comment]
Супер, аз след 15ина минутки ще съм готов с бекъп/рестор нещата и ще ги изкатеря тук.

**Comment by svinqvmraka** [comment]
бекъп и рестор скриптовете са малко по-подредени вече и имат статуси накрая, в случай че нещо е фейлнало. Малко по-късно днес ще ги променя по модела на твойте промени в install.sh. До тогава, скриптовете очакват да се намират в `%webroot%/opendata-cms/backup-restore/`, а пък сайта в `%webroot%/`.

**Comment by mitio** [comment]
FYI DNS-ът е работещ, URL-ът е live. 🎉

**Comment by svinqvmraka** [comment]
Тук мисля че сме готови, винаги има какво да се подобри, но нещата би трябвало да са работещи в момента. 

Имаме:
- install.sh - инсталационен скрипт, който инсталира сайта/ъпдейтва темата, ако вече е инсталиран.
- backup.sh - export-ва базата данни и архивира файловете на сайта
- restore.sh - възстановява sql файл, експортнат от backup.sh и разархивира файловете в root-а на сайта.

Не затварям issue-то, защото ми се иска да се тестват още нещата, за да е сигурно че не пропускам нещо.

**Comment by mitio** [comment]
Тествах `backup.sh` и мисля, че работи добре. Сложил съм го в един ежедневен крон.

Сега ще пробвам и да затрия сайта и да го възстановя с инсталация + restore. :)

P.S. Направих и малко дребни и стилистични корекции в `backup.sh` и `restore.sh` като единствената по-сериозна функционална промяна е, че "старите" копия на архивите на базата по подразбиране ги `gzip`-вам.

**Comment by mitio** [comment]
При restore има проблем с възстановяването на качени файлове, в чиито път/име има кирилица.

Разследвам.

EDIT: Не съм убеден, че е свързано с кирилицата. Разследването продължава.

**Comment by mitio** [comment]
Окей, мисля, че го оправих в add456fbe7df6d45eb848d6de8a4224b97eaee2c.

Backup & restore изглежда вече работят, считам въпроса за приключен.
