### ISSUE TITLE
Насочване на полето за търсене от хедъра към търсачката на портала

### ISSUE THREAD

**Issue by mitio** [governmentbg/opendata-cms#9]
Имаме две полета за търсене – едно в хедъра и едно в лявото меню.

Тъй като нямаме една обща търсачка, която да търси и в WordPress-а, и в портала, мисля, че е по-удачно полето за търсене в хедъра да го насочим към търсачката на портала (в момента сочи към .dev домейн).

Търсачката в лявото меню може да остане като търсачка в WP. Прегладам за да е максимално ясно какво се случва, заглавието на нейната кутийка да не е "Търсене", а "Търсене в новини и информация" (както се казва цялата секция).

**Comment by svinqvmraka** [comment]
Нещата в сайдбара са WordPress джаджи (от админ панела 'външен вид >> Джаджи'), като в момента са сложени произволни такива, за да не е празно. Има си драг&дроп интерфейс за тая работа, така че да се случва лесно всичко. Ще ги опишем тези неща в ръководството. 

За търсачките ми звучи смислено всичко, ще коментирам тук като съм готов.

**Comment by svinqvmraka** [comment]
Чудя се дали да не направим търсачката в ляво(тази, която ще търси във WordPress-а), голяма и над главния content, подобно на търсачката за организации на главната страница на портала.

Първоначално мислех че ще имаме само една търсачка и ми се стори излишно да правя още една огромна, но ако ще са две отделни, може би има някакъв смисъл. Пък и ще изглежда по-готино.

**Comment by mitio** [comment]
Идеята не е лоша и би довело до повече симетрия с оригиналния дизайн.

От друга страна, основната функция на портала е да предоставя набори от данни (а не новини), структурирани в някаква йерархия и един от най-удобните начини да намери човек набора, който търси, е търсачката там.

CMS частта се очаква да има както статични секции с информация (вероятно страници), така и новини (публикации). Когато става дума за новини, смятам, че толкова фокусирана търсачка над новините е по-скоро излишна, защото се предполага, че човек го интересуват най-много най-скорошните новини. Когато става дума за страници, търсачка би имала повече смисъл, но не очаквам да имаме чак толкова страници, а и тагове/категоризация вероятно биха били достатъчни като навигация.

На база на горното, аз не съм сигурен дали голяма търсачка в центъра на страницата е смислена за CMS частта. По-скоро бих оставил търсачката вляво.

**Comment by svinqvmraka** [comment]
Оукей, остава си вляво, само ще ѝ преведа placeholder-а в един момент(за което си има отделно ишу)

**Comment by svinqvmraka** [comment]
Вече си сочат на правилните места.
